apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: order-service-repo
  namespace: flux-system
spec:
  image: docker.io/quockidang1/order-service
  interval: 1m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: order-service-policy 
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: order-service-repo
  policy:
    alphabetical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: order-service-image-update
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@users.noreply.github.com
      messageTemplate: "chore: update image to {{range .Updated.Images}}{{.}}{{end}}"
    push:
      branch: main
  update:
    path: ./dev/order-service
    strategy: Setters
